### ISSUE TITLE
misplaced post..

### ISSUE THREAD

**Issue by erqan** [miguelfreitas/twister-html#330] opened 2015-11-23 13:29 UTC
sometimes new posts are misplaced in timeline...
![misplaced](https://cloud.githubusercontent.com/assets/12120467/11337584/bca84cfc-91f6-11e5-9c49-b0f2c3ad584c.png)

**Comment by slr** [comment] 2015-11-23 15:01
it would be good to have some instruction how to reproduce this. I didn't saw such glitches since  https://github.com/miguelfreitas/twister-html/commit/8feb66bc72bb5aa5d94956f76169054b66bf84a8

**Comment by erqan** [comment] 2015-11-27 11:17
i didn't investigate deeply but there seems to be no exact step to reproduce. it happened (at least i've noticed) two or three times while reading older posts in timeline.. and my client has that patch.

**Comment by slr** [comment] 2015-11-28 08:08
looks like it's enough to open mentions to see wrong posts' ordering (if you have enough 100+ mentions or something).

but I think it's fixed now, checkout https://github.com/miguelfreitas/twister-html/commit/5acb60a7c8313ae0316cf7143cf7f9882a1d1240

**Closed by slr** 2015-11-28 08:08 UTC
Labels: bug
