### ISSUE TITLE
invalid twistday date (local dates not match)

### ISSUE THREAD

**Issue by wrewolf** [miguelfreitas/twister-html#344] opened 2016-02-20 09:07 UTC
bug in
[/js/interface_home.js#L290](https://github.com/miguelfreitas/twister-html/blob/d9f21124c90a4195ec5ca9a5c13f6b44651f09a8/js/interface_home.js#L290)

bug on row with Denis Ryabov
![image](https://pp.vk.me/c627819/v627819119/3c737/bKZpIg0QYc4.jpg)

**Comment by slr** [comment] 2016-02-20 16:09
ok, let's call it bug. fix: https://github.com/miguelfreitas/twister-html/commit/c306ef440151fd2002c22fba62d45b5262185bbb

**Comment by slr** [comment] 2016-02-20 16:11
reopen until it will be merged into `master`

**Comment by slr** [comment] 2016-02-20 16:34
btw there's weird shit with @dryabov's UTC date of first twist, 1392933647:
*  result of `var t = new Date(0); t.setUTCSeconds(1392933647); t.toString().replace(/GMT.*/g, '')` (it's our *timeGmtToText()* in short) may vary in browsers. on Linux' Firefox:

  > Fri Feb 21 2014 04:00:47 

  in Linux' Chrome:

  > Fri Feb 21 2014 03:00:47 

  but result of `var t = new Date(0); t.setUTCSeconds(1392933647); t.toLocaleString()` in both these browsers:

  > 21.02.2014, 4:00:47

* in both browsers only for three years it's 04:00 AM in output for this:
  ```
  var d = new Date();
  d.setTime(0);
  d.setUTCSeconds(1392933647);
  for (var i = 2000; i < 2100; i++) {
      var t = new Date(0); t.setUTCSeconds(Date.UTC(i, d.getUTCMonth(), d.getUTCDate(), d.getUTCHours(), d.getUTCMinutes(), d.getUTCSeconds()) / 1000);
      console.log(t.toLocaleString());
  }
  ```
  it's like:

  > 21.02.2000, 3:00:47
21.02.2001, 3:00:47
…
21.02.2010, 3:00:47
21.02.2011, 3:00:47
21.02.2012, 4:00:47  // this one and two following only
21.02.2013, 4:00:47
21.02.2014, 4:00:47
21.02.2015, 3:00:47
21.02.2016, 3:00:47
…
21.02.2098, 3:00:47
21.02.2099, 3:00:47

**Comment by slr** [comment] 2016-03-25 00:55
ok, #348 is merged and therefore the issue is solved. thanks for the report and conversation in twister.

**Closed by slr** 2016-03-25 00:55 UTC
Labels: bug
